//
//  ToDoTasksListPresenter.swift
//  CleanSwiftExample
//
//  Created by Cesar Brenes on 6/6/17.
//  Copyright (c) 2017 César Brenes Solano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ToDoTasksListPresenterInput{
    func presentSomething(response: ToDoTasksList.Response)
}

protocol ToDoTasksListPresenterOutput: class{
    func displaySomething(viewModel: ToDoTasksList.ViewModel)
}

class ToDoTasksListPresenter: ToDoTasksListPresenterInput{
    weak var output: ToDoTasksListPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentSomething(response: ToDoTasksList.Response){
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = ToDoTasksList.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
