//
//  ToDoTasksListInteractor.swift
//  CleanSwiftExample
//
//  Created by Cesar Brenes on 6/6/17.
//  Copyright (c) 2017 César Brenes Solano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ToDoTasksListInteractorInput{
    func doSomething(request: ToDoTasksList.Request)
}

protocol ToDoTasksListInteractorOutput{
    func presentSomething(response: ToDoTasksList.Response)
}

class ToDoTasksListInteractor: ToDoTasksListInteractorInput{
    var output: ToDoTasksListInteractorOutput!
    var worker: ToDoTasksListWorker!
    
    // MARK: Business logic
    
    func doSomething(request: ToDoTasksList.Request){
        // NOTE: Create some Worker to do the work
        
        worker = ToDoTasksListWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = ToDoTasksList.Response()
        output.presentSomething(response: response)
    }
}
