//
//  ToDoTasksListViewController.swift
//  CleanSwiftExample
//
//  Created by Cesar Brenes on 6/6/17.
//  Copyright (c) 2017 César Brenes Solano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ToDoTasksListViewControllerInput{
    func displaySomething(viewModel: ToDoTasksList.ViewModel)
}

protocol ToDoTasksListViewControllerOutput{
    func doSomething(request: ToDoTasksList.Request)
}

class ToDoTasksListViewController: UIViewController, ToDoTasksListViewControllerInput{
    var output: ToDoTasksListViewControllerOutput!
    var router: ToDoTasksListRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib(){
        super.awakeFromNib()
        ToDoTasksListConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad(){
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad(){
        // NOTE: Ask the Interactor to do some work
        
        let request = ToDoTasksList.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: ToDoTasksList.ViewModel){
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}
