//
//  ToDoTasksListWorker.swift
//  CleanSwiftExample
//
//  Created by Cesar Brenes on 6/6/17.
//  Copyright (c) 2017 César Brenes Solano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ToDoTasksListWorker{
    // MARK: Business Logic
    
    var taskArray :[ToDoTasksList.Task] = []
    
    func multiply(number:String) -> Int{
        return Int(number)! * 2
    }
    
    
    func getDataSource() -> [ToDoTasksList.Task]{
        if taskArray.count == 0{
            taskArray.append(ToDoTasksList.Task(text: "TO DO #1", counter: 1))
            taskArray.append(ToDoTasksList.Task(text: "TO DO #2", counter: 2))
            taskArray.append(ToDoTasksList.Task(text: "TO DO #3", counter: 3))
        }
        return taskArray
    }
}
